import uuid
from datetime import datetime
from enum import Enum as PyEnum

from sqlalchemy import String, Boolean, DateTime, Enum, ForeignKey, func, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class TargetStatus(str, PyEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"


class Target(Base):
    __tablename__ = "targets"

    id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Target personal info
    email: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    full_name: Mapped[str] = mapped_column(String(255), nullable=False)
    department: Mapped[str | None] = mapped_column(String(100), nullable=True)
    job_title: Mapped[str | None] = mapped_column(String(255), nullable=True)
    manager_name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Personalised email content (generated by Personalisation Agent)
    personalised_subject: Mapped[str | None] = mapped_column(String(500), nullable=True)
    personalised_body: Mapped[str | None] = mapped_column(String(10000), nullable=True)

    # Unique tracking token for this target in this campaign
    tracking_token: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)

    # Delivery status
    status: Mapped[TargetStatus] = mapped_column(Enum(TargetStatus), default=TargetStatus.PENDING)
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    failed_reason: Mapped[str | None] = mapped_column(String(500), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    # Foreign keys
    campaign_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("campaigns.id", ondelete="CASCADE"), index=True
    )
    organization_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("organizations.id", ondelete="CASCADE"), index=True
    )

    # Relationships
    campaign: Mapped = relationship("Campaign", back_populates="targets")
    tracking_events: Mapped[list["TrackingEvent"]] = relationship("TrackingEvent", back_populates="target")
